'use strict';
const C=document.querySelector('#game'),g=C.getContext('2d'),screen=document.querySelector('#screen');
const W=1280,H=720,world=4400,keys={},pressed={},imgs={};
const roster=[{name:'IGNIS',role:'Equilibrato',color:'#ff6255',power:1,speed:265},{name:'AZUR',role:'Tecnico',color:'#639dff',power:.95,speed:280},{name:'LYRA',role:'Veloce',color:'#f5d34f',power:.9,speed:310},{name:'AURA',role:'Energia',color:'#ff7bbc',power:.95,speed:285},{name:'ONYX',role:'Potente',color:'#b7c7d7',power:1.25,speed:235}];
let mode='loading',chosen=0,player,enemies=[],props=[],fx=[],drops=[],camera=0,time=0,zone=0,score=0,kills=0,combo=0,comboTimer=0,shake=0,flash=0,elapsed=0,checkpoint=0,muted=false,audio,beat=0,padPrevious=[],introPage=0;
const zones=[{x:760,name:'IL LUNGOMARE',n:4},{x:1710,name:'LA STRADA DEL PORTO',n:6},{x:2740,name:'IL CANCELLO',n:7},{x:3730,name:'MASTICE',n:1}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function sound(f=160,d=.08,type='square',vol=.035){if(muted||!audio)return;const o=audio.createOscillator(),a=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,f*.45),audio.currentTime+d);a.gain.setValueAtTime(vol,audio.currentTime);a.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(a);a.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function unlock(){if(!audio)try{audio=new(window.AudioContext||window.webkitAudioContext)()}catch(e){}audio?.resume()}
function ui(html,cls=''){screen.className=cls;screen.innerHTML=html;screen.querySelector('button')?.focus()}
function foot(){return '<div class="footer">SVILUPPATO ED IDEATO DA b3pZ · V0.1 · PORTO AURORA</div>'}
function menu(){mode='menu';ui('<div class="eyebrow">UN ARCADE TOKUSATSU ORIGINALE</div><h1>PRIMAL<br><span>SENTINELS</span></h1><p>Una città sotto assedio. Cinque Cuori risvegliati.<br>La prima notte di una guerra dimenticata.</p><nav><button class="primary" id="play">INIZIA LA STORIA</button><button id="select">SCELTA EROE</button><button id="help">COMANDI</button></nav><p class="small">PC · Tastiera e controller · Capitolo 01 / 08<br>Questa build è per un giocatore. Cooperativa online in sviluppo.</p>'+foot());document.querySelector('#play').onclick=()=>{unlock();introPage=0;intro()};document.querySelector('#select').onclick=selection;document.querySelector('#help').onclick=help}
function help(){mode='help';ui('<span class="eyebrow">ADDESTRAMENTO</span><h2>Entra. Colpisci. Spostati.</h2><p class="help"><kbd>WASD</kbd> / <kbd>↑↓←→</kbd> Muoviti · <kbd>J</kbd> Pugno e combo<br><kbd>K</kbd> Calcio · <kbd>Spazio</kbd> Salto / calcio aereo<br><kbd>L</kbd> Speciale (40 energia) · <kbd>Shift</kbd> Schivata<br><kbd>Esc</kbd> Pausa · <kbd>M</kbd> Audio<br><br>Controller: stick / croce direzionale · X pugno · Y calcio · A salto · B speciale · RB schivata · Start pausa.<br>Allineati al nemico in profondità per colpirlo. Esci dal cerchio arancione prima che Mastice colpisca. Le casse contengono cure.</p><nav><button id="back">TORNA AL MENU</button></nav>');document.querySelector('#back').onclick=menu}
const story=[['PORTO AURORA · ORE 23:47','La notte delle sirene','La frattura apparve sopra il mare. Poi gli uomini senza volto uscirono dagli specchi. Nessuno sapeva cosa cercassero.'],['OLTRE IL VELO','Una voce dimenticata','«Riportatemi i Cuori.» Vespera pronunciò cinque nomi. Sotto la città, macchine addormentate da millenni risposero.'],['IL RISVEGLIO','Non siete soli','Cinque armature si accesero. Il porto era già in fiamme. Prima di scoprire chi li avesse scelti, i nuovi Sentinels dovevano salvare la loro città.']];
function intro(){mode='intro';let s=story[introPage];ui(`<span class="eyebrow">${s[0]}</span><h2>${s[1]}</h2><p>${s[2]}</p><nav><button class="primary" id="next">${introPage===2?'SCEGLI IL SENTINEL':'CONTINUA'}</button><button id="skip">SALTA INTRO</button></nav>`);document.querySelector('#next').onclick=()=>{introPage++;introPage>2?selection():intro()};document.querySelector('#skip').onclick=selection}
function selection(){mode='select';ui('<span class="eyebrow">CINQUE CUORI · UNA SQUADRA</span><h2>Scegli il tuo Sentinel</h2><div class="cards">'+roster.map((r,i)=>`<button class="card ${i===chosen?'selected':''}" data-i="${i}"><canvas width="181" height="181"></canvas><b>${r.name}</b><small>${r.role}</small></button>`).join('')+'</div><p id="desc">Ogni eroe ha velocità e potenza diverse. L’armatura che vedi qui è quella che userai in battaglia.</p><nav><button class="primary" id="go">ENTRA A PORTO AURORA</button><button id="back">MENU</button></nav>');screen.querySelectorAll('.card').forEach((b,i)=>{b.querySelector('canvas').getContext('2d').drawImage(imgs.fighters,0,i*181,181,181,0,0,181,181);b.onclick=()=>{chosen=i;selection()}});document.querySelector('#go').onclick=()=>{unlock();start()};document.querySelector('#back').onclick=menu}
function makePlayer(){return{x:170,y:575,hp:130,max:130,energy:60,face:1,z:0,vz:0,cool:0,attack:0,kind:'',hit:false,inv:0,dodge:0,walk:0,stun:0}}
function start(cp=0){player=makePlayer();enemies=[];fx=[];drops=[];zone=cp;checkpoint=cp;score=0;kills=0;combo=0;elapsed=0;camera=0;player.x=cp?zones[cp-1].x+260:170;props=[450,1130,1400,2100,2480,3180,3420].filter(x=>x>player.x).map((x,i)=>({x,y:620-i%2*95,hp:2}));mode='play';screen.className='hidden';spawnZone();banner(zones[zone].name);Object.keys(keys).forEach(k=>keys[k]=false)}
function spawnZone(){let a=zones[zone];for(let i=0;i<a.n;i++){let boss=zone===3;enemies.push({x:a.x+180+i%3*120,y:495+(i%4)*47,hp:boss?560:zone===2?76:60,max:boss?560:zone===2?76:60,boss,face:-1,walk:0,cool:1+i*.35,wind:0,attack:0,stun:0,inv:0,dead:0,target:null,slam:false})}}
function banner(t){fx.push({type:'banner',text:t,life:2.8,max:2.8})}
function pause(){if(mode==='play'){mode='pause';ui('<span class="eyebrow">PAUSA</span><h2>Il porto può aspettare.</h2><nav><button class="primary" id="resume">RIPRENDI</button><button id="retry">RIPARTI DAL CHECKPOINT</button><button id="back">MENU</button></nav>','center');document.querySelector('#resume').onclick=resume;document.querySelector('#retry').onclick=()=>start(checkpoint);document.querySelector('#back').onclick=menu}else if(mode==='pause')resume()}
function resume(){mode='play';screen.className='hidden';pressed.Escape=false}
function end(win){mode=win?'win':'lose';if(win)try{localStorage.setItem('primal-level1','complete')}catch(e){}ui(`<span class="eyebrow">${win?'CAPITOLO 01 COMPLETATO':'IL CUORE È ANCORA ACCESO'}</span><h2>${win?'Il porto è salvo. Per ora.':'Rialzati, Sentinel.'}</h2><p>${win?'Tra i resti di Mastice trovi un simbolo inciso anche nella tua armatura. La scienziata rapita è su un convoglio diretto oltre il Velo.<br><br>PROSSIMO CAPITOLO · IL CONVOGLIO DEI PRIGIONIERI':'Mastice cerca qualcosa sotto il porto. Torna al checkpoint e cambia tattica.'}</p><p>PUNTEGGIO ${score} · NEMICI ${kills} · TEMPO ${Math.floor(elapsed/60)}:${String(Math.floor(elapsed%60)).padStart(2,'0')}</p><nav><button class="primary" id="again">${win?'GIOCA ANCORA':'RIPROVA DAL CHECKPOINT'}</button><button id="back">MENU</button></nav>`,'center');document.querySelector('#again').onclick=()=>start(win?0:checkpoint);document.querySelector('#back').onclick=menu}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)fx.push({type:'spark',x,y,vx:(Math.random()-.5)*400,vy:(Math.random()-.6)*300,life:.3+Math.random()*.2,color})}
function attack(kind){if(player.cool>0||player.stun>0||player.dodge>0)return;if(kind==='special'&&player.energy<40){sound(80);return}player.kind=kind;player.attack=kind==='special'?.6:.32;player.cool=kind==='special'?.8:kind==='kick'?.48:.32;player.hit=false;if(kind==='special'){player.energy-=40;player.inv=.6;flash=.15;sound(550,.35,'sawtooth')}else sound(kind==='kick'?160:220)}
function damage(e,amount){if(e.hp<=0||e.inv>0)return;e.hp-=amount;e.stun=e.boss?.13:.35;e.inv=.12;e.x+=player.face*(e.boss?8:25);burst(e.x,e.y-75,e.boss?'#ffbe52':'#a684ff');shake=e.boss?7:3;combo++;comboTimer=2;score+=Math.round(amount*5);player.energy=Math.min(100,player.energy+5);sound(85,.1,'sawtooth');if(e.hp<=0){e.dead=.65;kills++;score+=e.boss?2000:200;if(kills%3===0)drops.push({x:e.x,y:e.y,type:'energy',life:20})}}
function hurt(amount){if(player.inv>0||player.hp<=0)return;player.hp-=amount;player.inv=.85;player.stun=.2;combo=0;shake=8;burst(player.x,player.y-75,'#ff685d');sound(60,.15,'sawtooth');if(player.hp<=0)end(false)}
function pollPad(){let p=navigator.getGamepads?.()[0];if(!p){keys.padL=keys.padR=keys.padU=keys.padD=false;return}let b=p.buttons.map(b=>b.pressed);if(mode!=='play'&&mode!=='pause'){if((b[0]&&!padPrevious[0]))document.activeElement?.click();if((b[15]&&!padPrevious[15])||(b[13]&&!padPrevious[13])){let bs=[...screen.querySelectorAll('button')],i=bs.indexOf(document.activeElement);bs[(i+1)%bs.length]?.focus()}if((b[14]&&!padPrevious[14])||(b[12]&&!padPrevious[12])){let bs=[...screen.querySelectorAll('button')],i=bs.indexOf(document.activeElement);bs[(i-1+bs.length)%bs.length]?.focus()}}const map={0:'Space',1:'KeyL',2:'KeyJ',3:'KeyK',5:'ShiftLeft',9:'Escape'};for(let n in map){if(b[n]&&!padPrevious[n])pressed[map[n]]=true}keys.padL=p.axes[0]<-.25||b[14];keys.padR=p.axes[0]>.25||b[15];keys.padU=p.axes[1]<-.25||b[12];keys.padD=p.axes[1]>.25||b[13];padPrevious=b}
function update(dt){pollPad();if(pressed.Escape)pause();if(pressed.KeyM)muted=!muted;if(mode!=='play'){for(let k in pressed)delete pressed[k];return}elapsed+=dt;time+=dt;let p=player,r=roster[chosen];for(let key of ['cool','inv','stun','dodge'])p[key]=Math.max(0,p[key]-dt);comboTimer-=dt;if(comboTimer<=0)combo=0;
let dx=(keys.KeyD||keys.ArrowRight||keys.padR?1:0)-(keys.KeyA||keys.ArrowLeft||keys.padL?1:0),dy=(keys.KeyS||keys.ArrowDown||keys.padD?1:0)-(keys.KeyW||keys.ArrowUp||keys.padU?1:0);
if(pressed.Space&&p.z===0&&p.stun===0){p.vz=520;sound(300,.1,'triangle')}if(pressed.ShiftLeft&&p.cool===0&&p.z===0){p.dodge=.24;p.inv=.35;p.cool=.65;sound(180,.08,'triangle')}
if(pressed.KeyJ)attack(p.z>0?'air':'punch');if(pressed.KeyK)attack('kick');if(pressed.KeyL)attack('special');
if(p.stun===0){let len=Math.hypot(dx,dy)||1,s=r.speed*(p.attack>0?.35:1);p.x+=dx/len*s*dt;p.y+=dy/len*s*.65*dt;if(dx)p.face=dx;p.walk+=dt*(dx||dy?9:0);if(p.dodge)p.x+=p.face*650*dt}
p.moving=!!(dx||dy);
p.x=clamp(p.x,Math.max(50,camera+35),Math.min(world-100,zones[zone].x+620));p.y=clamp(p.y,480,668);p.z=Math.max(0,p.z+p.vz*dt);if(p.z>0)p.vz-=1300*dt;else p.vz=0;
if(p.attack>0){p.attack-=dt;if(!p.hit&&p.attack<(p.kind==='special'?.46:.21)){p.hit=true;let special=p.kind==='special';enemies.forEach(e=>{if(e.hp>0&&Math.abs(e.y-p.y)<(special?150:46)&&Math.abs(e.x-p.x)<(special?230:p.kind==='kick'?135:105)&&(special||(e.x-p.x)*p.face>-20))damage(e,(special?65:p.kind==='kick'?25:18)*r.power)});props.forEach(o=>{if(o.hp>0&&Math.abs(o.x-p.x)<130&&Math.abs(o.y-p.y)<50){o.hp--;burst(o.x,o.y-20,'#c7a677');if(!o.hp){drops.push({x:o.x,y:o.y,type:'health',life:40});score+=75}}});if(special){fx.push({type:'ring',x:p.x,y:p.y-60,life:.5,max:.5,color:r.color});shake=10}}}
for(let e of enemies){for(let key of ['cool','stun','inv','attack'])e[key]=Math.max(0,e[key]-dt);if(e.hp<=0){e.dead-=dt;continue}let dx=p.x-e.x,dy=p.y-e.y;e.face=dx>=0?1:-1;if(e.wind>0){e.wind-=dt;if(e.wind<=0){e.attack=.32;if(e.slam){burst(e.target.x,e.target.y,'#ffb24c',30);fx.push({type:'ring',x:e.target.x,y:e.target.y,life:.45,max:.45,color:'#ffaa4c'});shake=12;if(Math.hypot(p.x-e.target.x,(p.y-e.target.y)*1.4)<120&&p.z<35)hurt(30)}else if(Math.abs(dx)<(e.boss?165:95)&&Math.abs(dy)<50&&p.z<65)hurt(e.boss?23:10);e.cool=e.boss?1.15:1.3}}else if(!e.stun&&!e.attack){let range=e.boss?140:72;if(Math.abs(dx)>range||Math.abs(dy)>25){let sp=e.boss?100:95+zone*15;e.x+=Math.sign(dx)*(Math.abs(dx)>range?sp*dt:0);e.y+=Math.sign(dy)*(Math.abs(dy)>15?sp*.6*dt:0);e.walk+=dt*7;e.moving=true}else if(e.cool===0){e.moving=false;e.wind=e.boss?.85:.5;e.slam=e.boss&&(e.hp<e.max*.5||Math.random()<.4);e.target={x:p.x,y:p.y};sound(e.boss?120:230,.12,'triangle')}}}
for(let d of drops){d.life-=dt;if(Math.hypot(p.x-d.x,p.y-d.y)<48){if(d.type==='health')p.hp=Math.min(p.max,p.hp+35);else p.energy=Math.min(100,p.energy+20);d.life=0;sound(650,.14,'sine')}}drops=drops.filter(d=>d.life>0);
if(enemies.every(e=>e.hp<=0&&e.dead<=0)){if(zone===3){end(true)}else if(p.x>zones[zone].x+380){zone++;checkpoint=zone;spawnZone();p.hp=Math.min(p.max,p.hp+18);banner(zones[zone].name)}}
camera=clamp(p.x-420,0,world-W);fx.forEach(f=>{f.life-=dt;if(f.type==='spark'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=700*dt}});fx=fx.filter(f=>f.life>0);shake=Math.max(0,shake-dt*30);flash=Math.max(0,flash-dt);p.energy=Math.min(100,p.energy+dt*1.6);beat+=dt;if(beat>.42){beat=0;sound([65,65,82,73][Math.floor(time/1.68)%4],.16,'triangle',.012)}for(let k in pressed)delete pressed[k];}
function sprite(row,frame,x,y,size=150,face=1,ctx=g){if(row===4&&frame===7)frame=4;ctx.save();ctx.translate(x,y);ctx.scale(face,1);ctx.imageSmoothingEnabled=false;ctx.drawImage(imgs.fighters,frame*181,row*181,181,181,-size/2,-size,size,size);ctx.restore()}
function bossSprite(frame,x,y,face,alpha=1){g.save();g.globalAlpha=alpha;g.translate(x,y);g.scale(face,1);let sw=imgs.mastice.width/4,sh=imgs.mastice.height/2;g.drawImage(imgs.mastice,frame%4*sw,Math.floor(frame/4)*sh,sw,sh,-135,-250,270,270);g.restore()}
function txt(text,x,y,size=18,color='#eef6ff',align='left'){g.fillStyle=color;g.font=`700 ${size}px system-ui`;g.textAlign=align;g.fillText(text,x,y)}
function bar(x,y,w,h,value,color){g.fillStyle='#142636';g.fillRect(x,y,w,h);g.fillStyle=color;g.fillRect(x,y,w*clamp(value,0,1),h)}
function backdrop(){if(['play','pause','win','lose'].includes(mode)){g.drawImage(imgs.port,-camera*.65,0,world*.65+W,720);g.fillStyle='#04112030';g.fillRect(0,0,W,H)}else{let q=mode==='intro'?introPage:0,sx=0,sy=q===2?443:0;g.drawImage(imgs.story,sx,sy,887,443,0,0,W,H);g.fillStyle='#05102055';g.fillRect(0,0,W,H);if(q===1){let im=imgs['campaign-villains'];g.drawImage(im,0,im.height/7*5,im.width/6,im.height/7,820,160,300,400)}}}
function render(){g.clearRect(0,0,W,H);if(!imgs.port)return;backdrop();if(!player||!['play','pause','win','lose'].includes(mode))return;g.save();if(shake)g.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);g.translate(-camera,0);
for(let e of enemies)if(e.wind>0){g.save();g.strokeStyle=e.boss?'#ffb657':'#ed687d';g.lineWidth=3;g.setLineDash([7,5]);g.beginPath();g.ellipse(e.slam?e.target.x:e.x,e.slam?e.target.y:e.y,e.boss?115:70,30,0,0,Math.PI*2);g.stroke();g.restore()}
let objects=[...props.filter(o=>o.hp>0).map(o=>({...o,type:'crate'})),...enemies.filter(e=>e.hp>0||e.dead>0).map(e=>({...e,type:'enemy'})),{...player,type:'player'}].sort((a,b)=>a.y-b.y);
for(let o of objects){g.fillStyle='#02081566';g.beginPath();g.ellipse(o.x,o.y+3,o.boss?80:38,10,0,0,Math.PI*2);g.fill();if(o.type==='crate'){g.fillStyle='#76523a';g.fillRect(o.x-24,o.y-45,48,45);g.strokeStyle='#c7945b';g.lineWidth=3;g.strokeRect(o.x-24,o.y-45,48,45);g.beginPath();g.moveTo(o.x-23,o.y-44);g.lineTo(o.x+23,o.y);g.stroke();continue}let isP=o.type==='player';let frame=o.stun>0?7:o.attack>0?(isP?(o.kind==='kick'||o.kind==='air'?6:o.attack>.21?4:5):5):o.wind>0?4:o.z>0?6:o.moving?1+Math.floor(o.walk)%3:0;g.save();if(o.hp<=0)g.globalAlpha=Math.max(0,o.dead/.65);if(isP&&o.inv>0&&Math.floor(time*18)%2)g.globalAlpha=.55;if(o.boss){frame=o.hp<=0?7:o.stun?6:o.wind?3:o.attack?(o.slam?5:4):Math.floor(o.walk)%3;bossSprite(frame,o.x,o.y,o.face)}else sprite(isP?chosen:5,frame,o.x,o.y-(o.z||0),150,o.face);g.restore();if(!isP&&o.hp>0&&!o.boss)bar(o.x-27,o.y-157,54,4,o.hp/o.max,'#a398e8')}
for(let d of drops){g.fillStyle=d.type==='health'?'#7bf0b1':'#77ceff';g.save();g.translate(d.x,d.y-18+Math.sin(time*4)*4);g.rotate(Math.PI/4);g.fillRect(-9,-9,18,18);g.restore();txt(d.type==='health'?'+':'ϟ',d.x,d.y-12,17,'#10212d','center')}
for(let f of fx){g.globalAlpha=Math.min(1,f.life*3);if(f.type==='spark'){g.fillStyle=f.color;g.fillRect(f.x,f.y,5,5)}if(f.type==='ring'){g.strokeStyle=f.color;g.lineWidth=6;g.beginPath();g.ellipse(f.x,f.y,220*(1-f.life/f.max),90*(1-f.life/f.max),0,0,7);g.stroke()}g.globalAlpha=1}
if(enemies.every(e=>e.hp<=0)&&zone<3)txt('AVANTI  →',camera+W-165,380,26,'#ffe0a0');g.restore();
g.fillStyle='#071320d9';g.fillRect(24,23,340,95);sprite(chosen,0,65,114,80);txt(roster[chosen].name,112,49,18,roster[chosen].color);bar(112,61,225,15,player.hp/player.max,'#6fdfb3');bar(112,86,225,7,player.energy/100,'#69aeee');txt('01 / 08   PORTO AURORA',W-30,44,16,'#e2e9ed','right');txt(String(score).padStart(7,'0'),W-30,76,27,'#f3bd75','right');if(combo>1)txt(combo+' HIT',W-30,113,22,'#fff1c6','right');txt('WASD  MUOVI     J  PUGNO     K  CALCIO     SPAZIO  SALTO     L  SPECIALE     SHIFT  SCHIVA     ESC  PAUSA',640,702,12,'#b8c8d7','center');let b=enemies.find(e=>e.boss&&e.hp>0);if(b){txt('MASTICE · IL CUSTODE DEL PORTO',640,44,15,'#ffbe75','center');bar(445,57,390,13,b.hp/b.max,'#eb9052');if(b.hp<b.max*.5)txt('ARMATURA INSTABILE',640,92,12,'#ffc67f','center')}let ban=fx.find(f=>f.type==='banner');if(ban){g.fillStyle='#071522bd';g.fillRect(300,150,680,70);txt(ban.text,640,196,28,'#f5dcad','center')}if(flash){g.fillStyle='#c0eaff55';g.fillRect(0,0,W,H)}}
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!keys[e.code])pressed[e.code]=true;keys[e.code]=true});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{for(let k in keys)keys[k]=false;if(mode==='play')pause()});
let last=0;function loop(t){let dt=Math.min(.033,(t-last)/1000||.016);last=t;update(dt);render();requestAnimationFrame(loop)}
Promise.all(['fighters','mastice','port','story','campaign-villains'].map(name=>new Promise((resolve,reject)=>{let i=new Image();i.onload=()=>{imgs[name]=i;resolve()};i.onerror=()=>reject(name);i.src='assets/'+name+'.png'}))).then(()=>{document.querySelector('#loading').remove();menu();requestAnimationFrame(loop)}).catch(name=>{document.querySelector('#loading').textContent='File mancante: '+name+'.png. Estrai tutto lo ZIP prima di aprire index.html.'});
// Read-only diagnostics, useful for browser verification.
window.gameStatus=()=>({mode,zone,score,kills,player:player?{x:player.x,y:player.y,hp:player.hp,energy:player.energy}:null,enemies:enemies.filter(e=>e.hp>0).length});
