import json, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
from PIL import Image
from pack import pack
import items, people
exec(open('build_sheets.py').read())
import build_hd
hd = build_hd.item_frames()
hd_keys = {k for k, *_ in hd}
fr = [f for f in items.build() if f[0] not in hd_keys] + hd
atlas, meta = pack(fr); atlas.save(OUT + 'items.png', optimize=True); META['items'] = meta
fr = build_hd.people_frames()
atlas, meta = pack(fr); atlas.save(OUT + 'people.png', optimize=True); META['people'] = meta
print('items', len(META['items']), 'people', len(META['people']))
src = Image.open(os.path.join(ROOT, 'assets', 'source', 'story.png')).convert('RGB')
for i, n in enumerate(['story_port', 'story_vespera', 'story_cores', 'story_heroes']):
    if n != 'story_cores':
        continue  # only the chamber of the cores is used by the cinematics
    src.crop(((i % 2) * 887, (i // 2) * 444, (i % 2) * 887 + 887, (i // 2) * 444 + 443)).save(os.path.join(ROOT, 'assets', 'bg', n + '.jpg'), quality=90)
js = '// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n'
open(os.path.join(ROOT, 'js', 'atlas.js'), 'w').write(js)
print(len(js))
